# config.yaml

# --- Hardware & General ---
num_gpus: 2
num_workers: 16

# --- Training settings ---
epochs: 80
batchsize: 8
lr: 0.0001
lrdf: 0.5
lrdp: 25
chkpointperiod: 1
trimages: 0
val_frq: 1
patchnum: 1
patchsz: 256

# --- Model & input settings ---
model: fullpipeline
input_type: ms_mosaic_inline_w_rgb
sr: false
out_special: null
backbone: restormer

# --- Paths & checkpointing ---
trdir: /datasets/ms_quantized
odir: /datasets/sai/spectral_demosaic_network_outputs
load: PyTorch/models/fullpipeline_restormer_enhancernaf_deform_ms_mosaic_inline_w_rgb_11-10-1-5-8/best.pth
job_id: null

# --- Testing & visualization ---
test: true
plot_images: false
